name: 😇 问题反馈
description: 使用 Layui 过程中遇到的 Bug、异常或其他困惑。
body:
  - type: markdown
    attributes:
      value: |
        **系统提示**：此处只接受 Layui 相关技术问题，其他如 layuiAdmin 或 LayIM 等主题相关问题请勿在此反馈。
  - type: checkboxes
    attributes:
      label: 议题条件
      options:
        - label: 我确认已查看官方使用文档：**https://layui.dev** ，但没有找到相关解决方案。
          required: true
        - label: 我确认已在 **Issues** 中搜索过类似的问题，但没有找到相关解决方案。
          required: true
  - type: input
    attributes:
      label: 版本号
      placeholder: 请提供您所使用的 Layui 版本号
    validations:
      required: true
  - type: input
    attributes:
      label: 浏览器
      placeholder: 如：Chrome 116.0.5845.111（正式版本） （64 位）
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: 问题类型
      options:
        - 疑是 BUG
        - 报错提示
        - 功能困惑
    validations:
      required: true
  - type: textarea
    attributes:
      label: 问题描述
      placeholder: 请提供详细的问题描述和操作步骤等信息，以便我们也能够更轻松地将问题复现。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 业务代码
      description: 直接粘贴问题对应的 `HTML,CSS,JavaScript` 等代码到下面的文本框，无需书写 `Markdown`
      placeholder: 请提供与该问题对应的业务代码片段，以便我们更好地排查问题。
      render: auto
    validations:
      required: true
  - type: textarea
    attributes:
      label: 截图补充
      placeholder: 如上述仍然无法准确地表述问题，可提供必要的截图（可直接粘贴上传）
  - type: input
    attributes:
      label: 演示地址
      description: 若能提供 Stackblitz, CodePen 或自主搭建的页面演示地址，将更有助于解决问题
      placeholder: URL
  - type: checkboxes
    attributes:
      label: 友好承诺
      options:
        - label: 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。
          required: true
